version: '3.8'

services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run dev

  production:
    build:
      context: ./docker
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    command: npm start